### ISSUE TITLE
Faces plugin: Delegates cannot be marshaled from native code into a domain other than their home domain.

### ISSUE THREAD

**Issue by nillis** [imazen/resizer#138]
The faces plugin sometimes causes the following exception:

![image](https://cloud.githubusercontent.com/assets/2675228/7345184/97c96782-ecd2-11e4-83e8-7a8451634707.png)

As suggested on the plugin page, we disabled overlapped recycle on the application pool which also contains only 1 application. 
Any suggestions on how to solve this problem?

![image](https://cloud.githubusercontent.com/assets/2675228/7345196/ad6920e6-ecd2-11e4-97c4-937072c4680a.png)

**Comment by nathanaeljones** [comment]
Somehow it's still re-using the operating system process for a new AppDomain. I don't have any suggestions right now. You might contact support and set up a session to review your configuration and environment.

**Comment by ghost** [comment]
@nathanaeljones  @nillis MsTest is re-using the Test Host process by design (vstesthost.exe in older version, or in vs14.0/2015 vstest.executionengine.exe)

As you've encountered, this breaks calling native dll's, since the dll isn't re-loaded and now is "across app domains" ... I wouldn't call it a fix, but a simple workaround is 

- **Test-->Test Settings-->Keep Execution Engine Running**  (uncheck it)

With a new test-host loaded for each class, the appdomain issue is moot because the native code must be re-mapped-in.

**Comment by JessePreiner** [comment]
What am I missing? What does that have to do with MsTest?
