### ISSUE TITLE
Use in an Asp.Net Core app targeting full .NET

### ISSUE THREAD

**Issue by mrahhal** [imazen/resizer#188]
I have an Asp.Net Core app targeting full .NET and running on windows (so we can really consider it a normal non-web application). I have a need to crop and resize images in process. Right now I'm using GDI+ but of course it has lots of problems in a web based app (global locks).

It'll be good enough to at least manually call the api instead of using the URL api. So can imageresizer be at all used in such an app?

**Comment by DaffittTech** [comment]
I too have been looking for an image resizer solution that I can use in my Asp.Net Core MVC web application. My question is whether or not (or when) there will be a NuGet Package version of the ImageResizer that is compatible with the Asp.Net Core MVC.

**Comment by lilith** [comment]
@mrahhal I would definitely give it a try. If .NET full is available, then the right APIs should be available for ImageResizer. 

As far as ASP.NET core compatibility, our plan is to base that on [Imageflow](https://github.com/imazen/imageflow) instead of ImageResizer 4. But an exact port of ImageResizer 4 to .NET Core wouldn't be possible, although we expect to have near-perfect URL compatibility - just not ASP.NET integration parity, as ASP.NET integration has been completely changed with Core.
