### ISSUE TITLE
RemoteReaderPlugin behavior not the same in async and synch paths

### ISSUE THREAD

**Issue by sixten** [imazen/resizer#234]
It took me an embarrassingly long time to realize that the realize that the reason why requests coming from the `RemoteReaderPlugin` didn't have a User-Agent header, despite the [revision history clearly showing](https://github.com/imazen/resizer/commit/08b67fae003f53b9ed48662725e955753a93e242#diff-5afd98783ec8e34bf16cbead1c150f53) that added months ago, was that there are two code paths—`GetUriStream()` and `GetUriStreamAsync()`—only one of which was adding this header (and we were on the other one).

Looking at the two methods side by side, they also appear to handle redirects very differently: the async version sets `AllowAutoRedirect` and `MaximumAutomaticRedirections`, while the synchronous version inspects the response and calls itself recursively to handle redirects.

Are either of these differences intentional? Would you accept a pull request that factors out the request construction and response handling code so it's the same? If so, which version of the redirect handling is the one you'd like to keep?

(Under more of an enhancement heading, is there a strong reason to stay with `HttpWebRequest` over `HttpClient`?)

**Comment by lilith** [comment]
The user agent difference was not intentional; I didn't notice it when reviewing the [PR](https://github.com/imazen/resizer/commit/08b67fae003f53b9ed48662725e955753a93e242#diff-5afd98783ec8e34bf16cbead1c150f53)

I'm not sure why, in 2012, that I manually implemented redirects. Perhaps I'd encountered a bug in the default implementation? But given the async impl hasn't had related issues AFAIK, perhaps we should unify them. 

Let's stick with the .NET implementation for now. I would accept a pull request that factors the handling out. Thank you!
